[global]
# Change this :)
auth_key = "swordfish"
address = "0.0.0.0"
port = 6677

[global.tls]
# To generate cartficate and key:
# openssl req -newkey rsa:2048 -x509 -keyout key.pem -out cert.pem -days 3650 -nodes -subj '/CN=localhost'
# Alternatively to this configuration, set the following environment variable:
# ROCKET_TLS={certs="cert.pem",key="key.pem"}
# or in PowerShell:
# $ENV:ROCKET_TLS='{certs="cert.pem",key="key.pem"}'
certs = "cert.pem"
key = "key.pem"
